M48
; DRILL file {KiCad 7.0.10} date Thu Feb 15 00:45:21 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-15T00:45:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
%
G90
G05
T1
X3.5Y2.89
X3.5Y-2.89
T2
X14.0Y-15.0
X14.5Y15.0
X26.0Y8.0
M30
